"""create initial schema

Revision ID: cc7eedf6a894
Revises: 
Create Date: 2026-10-04 20:56:09.294818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc7eedf6a894'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_datasets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('state_code', sa.CHAR(length=2), nullable=False),
    sa.Column('inventory_year', sa.SmallInteger(), nullable=False),
    sa.Column('source_format', sa.String(length=64), nullable=False),
    sa.Column('source_specification', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_file_name', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bridge_datasets')),
    sa.UniqueConstraint('source_sha256', name=op.f('uq_bridge_datasets_source_sha256'))
    )
    op.create_table('bridges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('state_code', sa.CHAR(length=2), nullable=False),
    sa.Column('structure_number', sa.String(length=15), nullable=False),
    sa.Column('county_code', sa.CHAR(length=3), nullable=False),
    sa.Column('facility_carried', sa.Text(), nullable=True),
    sa.Column('feature_crossed', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('source_latitude_code', sa.CHAR(length=8), nullable=True),
    sa.Column('source_longitude_code', sa.CHAR(length=9), nullable=True),
    sa.Column('year_built', sa.SmallInteger(), nullable=False),
    sa.Column('year_reconstructed', sa.SmallInteger(), nullable=True),
    sa.Column('average_daily_traffic', sa.Integer(), nullable=True),
    sa.Column('traffic_year', sa.SmallInteger(), nullable=True),
    sa.Column('truck_traffic_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lanes_on', sa.SmallInteger(), nullable=True),
    sa.Column('bridge_length_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('maximum_span_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('owner_code', sa.String(length=4), nullable=True),
    sa.Column('material_code', sa.String(length=4), nullable=True),
    sa.Column('design_type_code', sa.String(length=4), nullable=True),
    sa.Column('inspection_month', sa.SmallInteger(), nullable=True),
    sa.Column('inspection_year', sa.SmallInteger(), nullable=True),
    sa.Column('deck_condition_code', sa.CHAR(length=1), nullable=True),
    sa.Column('superstructure_condition_code', sa.CHAR(length=1), nullable=True),
    sa.Column('substructure_condition_code', sa.CHAR(length=1), nullable=True),
    sa.Column('culvert_condition_code', sa.CHAR(length=1), nullable=True),
    sa.Column('overall_condition_code', sa.CHAR(length=1), nullable=True),
    sa.Column('lowest_condition_rating', sa.SmallInteger(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("culvert_condition_code IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'N')", name=op.f('ck_bridges_culvert_condition_code_valid')),
    sa.CheckConstraint("deck_condition_code IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'N')", name=op.f('ck_bridges_deck_condition_code_valid')),
    sa.CheckConstraint("overall_condition_code IN ('G', 'F', 'P')", name=op.f('ck_bridges_overall_condition_code_valid')),
    sa.CheckConstraint("substructure_condition_code IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'N')", name=op.f('ck_bridges_substructure_condition_code_valid')),
    sa.CheckConstraint("superstructure_condition_code IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'N')", name=op.f('ck_bridges_superstructure_condition_code_valid')),
    sa.CheckConstraint('average_daily_traffic >= 0', name=op.f('ck_bridges_adt_nonnegative')),
    sa.CheckConstraint('bridge_length_m >= 0', name=op.f('ck_bridges_bridge_length_m_nonnegative')),
    sa.CheckConstraint('inspection_month >= 1 AND inspection_month <= 12', name=op.f('ck_bridges_inspection_month_range')),
    sa.CheckConstraint('lanes_on >= 0', name=op.f('ck_bridges_lanes_on_nonnegative')),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name=op.f('ck_bridges_latitude_range')),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name=op.f('ck_bridges_longitude_range')),
    sa.CheckConstraint('lowest_condition_rating >= 0 AND lowest_condition_rating <= 9', name=op.f('ck_bridges_lowest_condition_rating_range')),
    sa.CheckConstraint('maximum_span_m >= 0', name=op.f('ck_bridges_maximum_span_m_nonnegative')),
    sa.CheckConstraint('truck_traffic_percent >= 0 AND truck_traffic_percent <= 100', name=op.f('ck_bridges_truck_percent_range')),
    sa.ForeignKeyConstraint(['dataset_id'], ['bridge_datasets.id'], name=op.f('fk_bridges_dataset_id_bridge_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bridges')),
    sa.UniqueConstraint('dataset_id', 'state_code', 'structure_number', name='bridge_identity')
    )
    op.create_index('ix_bridges_dataset_adt', 'bridges', ['dataset_id', 'average_daily_traffic'], unique=False)
    op.create_index('ix_bridges_dataset_county', 'bridges', ['dataset_id', 'county_code'], unique=False)
    op.create_index('ix_bridges_dataset_overall_condition', 'bridges', ['dataset_id', 'overall_condition_code'], unique=False)
    op.create_index('ix_bridges_dataset_year_built', 'bridges', ['dataset_id', 'year_built'], unique=False)
    op.create_table('import_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=True),
    sa.Column('source_file_name', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_read', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_unchanged', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_rejected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warnings_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errors_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'completed_with_warnings', 'failed', 'skipped_duplicate_file')", name=op.f('ck_import_runs_status_valid')),
    sa.CheckConstraint('errors_count >= 0', name=op.f('ck_import_runs_errors_count_nonnegative')),
    sa.CheckConstraint('rows_inserted >= 0', name=op.f('ck_import_runs_rows_inserted_nonnegative')),
    sa.CheckConstraint('rows_read >= 0', name=op.f('ck_import_runs_rows_read_nonnegative')),
    sa.CheckConstraint('rows_rejected >= 0', name=op.f('ck_import_runs_rows_rejected_nonnegative')),
    sa.CheckConstraint('rows_unchanged >= 0', name=op.f('ck_import_runs_rows_unchanged_nonnegative')),
    sa.CheckConstraint('rows_updated >= 0', name=op.f('ck_import_runs_rows_updated_nonnegative')),
    sa.CheckConstraint('warnings_count >= 0', name=op.f('ck_import_runs_warnings_count_nonnegative')),
    sa.ForeignKeyConstraint(['dataset_id'], ['bridge_datasets.id'], name=op.f('fk_import_runs_dataset_id_bridge_datasets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_runs'))
    )
    op.create_table('import_issues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('structure_number', sa.String(length=15), nullable=True),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_record', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('warning', 'error', 'fatal')", name=op.f('ck_import_issues_severity_valid')),
    sa.CheckConstraint('row_number IS NULL OR row_number > 0', name=op.f('ck_import_issues_row_number_positive')),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], name=op.f('fk_import_issues_import_run_id_import_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_issues'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_issues')
    op.drop_table('import_runs')
    op.drop_index('ix_bridges_dataset_year_built', table_name='bridges')
    op.drop_index('ix_bridges_dataset_overall_condition', table_name='bridges')
    op.drop_index('ix_bridges_dataset_county', table_name='bridges')
    op.drop_index('ix_bridges_dataset_adt', table_name='bridges')
    op.drop_table('bridges')
    op.drop_table('bridge_datasets')
    # ### end Alembic commands ###
